### PR TITLE
add resource panos_ssl_decrypt_exclude_certificate_entry

### PR DESCRIPTION
**Pull request by TiantongHu**
## Description

add resource panos_ssl_decrypt_exclude_certificate_entry which manages SSL Decrypt Exclusion setting without toching other SSL decrypt settings

## Motivation and Context

#342 

## How Has This Been Tested?

Tested using the resource to modify ssl decryption exclusion with exsiting `forward_trust_certificate_rsa` and other ssl drcrypt settings, nothing gets changed except ssl decryption exclusion setting.
Tested create, update, delete. All working correctly (only changing ssl decrption exclusion)
Tested with resource `ssl_decrypt`, working as expected.

## Types of changes

- New feature (non-breaking change which adds functionality)

## Checklist

- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes if appropriate.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by TiantongHu** [comment]
Hi @shinmog , the PR is ready for review. Please let me know if anything needs to be changed :) thanks

**Comment by TiantongHu** [comment]
Hi @shinmog , is there anything that needs to be added?

**Review by shinmog — COMMENTED** [review]
I appreciate that you did documentation updates in this PR..!

But unfortunately this code has a race condition if used in real life.  If you look at the other code for modules that do `_entry` operations you'll see that they tend to use special functions that operate on individual members, which prevents race conditions if there are multiple `_entry` resources running at the same time.

Implementing a `panos_ssl_decrypt_exclude_certificate_entry` resource will require a pango SDK update first and foremost.

**Comment by TiantongHu** [comment]
> I appreciate that you did documentation updates in this PR..!
> 
> But unfortunately this code has a race condition if used in real life. If you look at the other code for modules that do `_entry` operations you'll see that they tend to use special functions that operate on individual members, which prevents race conditions if there are multiple `_entry` resources running at the same time.
> 
> Implementing a `panos_ssl_decrypt_exclude_certificate_entry` resource will require a pango SDK update first and foremost.

Hi, I'm working on pango changes. I see the `SslDecryptTrustedRootCaEntry` sets `ForceNew` to `true`. For `SslDecryptExcludeCertificateEntry`, does it matter to have an Update function? Is it OK to also set `ForceNew` to true?
Thanks

**Comment by TiantongHu** [comment]
I've updated the PR with another account in https://github.com/PaloAltoNetworks/terraform-provider-panos/pull/348
Please review that one instead. Tanks

**Pull request closed without merging**
